### ISSUE TITLE
[BUG] UnicodeEncodeError 

### ISSUE THREAD

**Issue by yavuzitconsulting** [yashrathi-git/pyHeadspace#1]
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)

This error occurs after the setup following your instructions, but using pip3 instead of pip.
OS is Ubuntu 20.04, my headspace was set to german.
It happens on any download command and after successful authorization.

I'm not a python expert in any way but i would say there's an encoding error in the response received by the server.
I think the change has to be made either in line 60 of main_py  
`session = requests.Session()`
where you probably can set the requests.encoding or maybe there is something like Session.encoding
or it's here in line 125
`response = session.get(url, params=params)`

Encoding should be ISO-8859-1 or maybe UTF8.

Sorry i could not be of any more help.

Edit: same happens on headspace pack --all and any other command!

See screenshot for details, it's one of my commands + output + resulting exception
![p0](https://user-images.githubusercontent.com/73593573/113702137-67e40b00-96d9-11eb-80bf-834abeaa0dc1.JPG)
![p1](https://user-images.githubusercontent.com/73593573/113702145-69adce80-96d9-11eb-919b-cce5ca75377b.JPG)
![p2](https://user-images.githubusercontent.com/73593573/113702153-6adefb80-96d9-11eb-857d-74b2a52ab0c4.JPG)

**Comment by yashrathi-git** [comment]
Make sure you are pasting the complete value for the bearer id(authentication token). 
Follow these [setup](https://github.com/yashrathi-git/pyHeadspace#setup) instructions. 
But to copy the bearer ID(authorization token), right-click on the authorization parameter without any text selected and use `copy value`. Please update if the issue persists.

**Comment by yavuzitconsulting** [comment]
Thanks, resolved.

Problem was manually copying the field in firefox, which would only take over the visible part of the token.
It has to be done like this:
(On Firefox)
Right click, "copy", paste to text editor and remove starting "authorization:"
exactly as you stated.

Thanks for your time and effort, nice tool.
BR
