### ISSUE TITLE
Donation link / email?

### ISSUE THREAD

**Issue by Cartogenic** [yashrathi-git/pyHeadspace#3]
Hi!

I'd like to donate money to support this project. I've been trying to code a script for this exact purpose, when I found this project. I'm amazed at the way it was developed. Its code reads like poetry.

Thanks in advance!

**Comment by yashrathi-git** [comment]
Thank you so much,
I am glad this script was able to help you. I am just a student, and I just wanted to help some people and also learn myself along the way. There is no way to donate, but I am glad, that it was able to help you:)
