### ISSUE TITLE
Headspace web app changed its routing

### ISSUE THREAD

**Issue by legarspol** [yashrathi-git/pyHeadspace#5]
I didn't get to use this script today. It looks like the headspace web app changed its URL format. Hence the script can't find the right ID in the URL. I tried to handcraft URLs and then give it to the script but I ended up downloading some random track 😅

**Comment by yashrathi-git** [comment]
Yes they updated the frontend. I would fix it soon. I haven't been getting enough time. 
The script still does work for downloading all packs and everyday meditations

**Comment by yashrathi-git** [comment]
Checkout the latest release v3.0.0, it has been fixed.

**Comment by yashrathi-git** [comment]
Closing this issue since it has been fixed

**Comment by legarspol** [comment]
Thank you! I got to make it work on v 3.0.2 :-)
