### ISSUE TITLE
Downloading from other languages?

### ISSUE THREAD

**Issue by naamex** [yashrathi-git/pyHeadspace#6]
Hi! Thank you so much for this code, it's exactly what I was looking for. I'm trying to download the Spanish version of one of the sessions, but when copying the link into the code it only downloads the English version.

Also, what's the default download directory for the files? Can't seem to find it. Thanks

**Comment by yashrathi-git** [comment]
there is no default download location. It downloads in the directory where you execute it. Try running `pwd` to get where your terminal is.

**Comment by naamex** [comment]
oh ok! Thanks! Got it. As far as the language, there's no current way to select it right? It just selects the English as default?

**Comment by yashrathi-git** [comment]
yes currently it could only download English

**Comment by flowni** [comment]
Really awesome project @yashrathi-git, thanks! 
@naamex for selecting languages you just have to adjust the header parameter "hs-languagepreference" to the desired one (e.g. "de-DE"). The header parameter "accept-language" does not need to be changed.

**Comment by naamex** [comment]
Hi @flowni! I actually discovered this a few days ago, is this on the __main__.py file right? I was able to change it, but when I went to download it said "Unauthorized" and the login didn't work
