### ISSUE TITLE
Some quick sessions won't download

### ISSUE THREAD

**Issue by naamex** [yashrathi-git/pyHeadspace#9]
This "quick meditation" session has a 1min, a 3min, and a 5 min version. The code treats the 3 versions as if they all lasted 1 minute, so it only downloads one of them. Any way to fix this? Thanks

![image](https://user-images.githubusercontent.com/97484438/151915191-f7522aa4-24e7-4cb6-95a3-c9870519c700.png)

**Comment by yashrathi-git** [comment]
This was a problem with rounding. Pyheadspace tries to get the duration from the session length. As session length don't exactly matches we check by  rounding off. Upgrading to latest version should fix this issue.

**Comment by naamex** [comment]
Wow thank you! Will download the new version 😊👍

**Comment by yashrathi-git** [comment]
If it's fixed for you could close this issue

**Comment by naamex** [comment]
oh sure.
